### ISSUE TITLE
Fix Watchlisting

### ISSUE THREAD

**Issue by lhl** [upcoming/upcoming-www#15]
See:
https://github.com/upcoming/upcoming-www/blob/master/controllers/watchlists.js#L11-L15
- How should watches be created
- Making sure it lists/get the status
- Don't create dupes
- Toggle properly

**Comment by lhl** [comment]
OK, here's what I did:
- watchlist items are stored in DB properly (w/ created_at and not duping)
- Adding and removing are now progressive (XHR w/ jQuery)
- Status is updated via AJAX for now (status set to either "attend" or "remove")
- Remove deletes the watchlist item; may want to consider logging that stuff somewhere for future data

TODO:
- Modify the event jade view stuff so that the static HTML reflects watchlist status properly

Watchlist nomenclature is a mess - the Watchlist model services a Watchlist (list of events) and also creates/modifies individual items... no me gusta, should have a standard naming/pattern since we have event and event lists as well, not going to deal w/ that, but making a note.

See:
https://github.com/upcoming/upcoming-www/commit/570739dbdf6b7fc3723e48d2e269558fe8b9d70b
https://github.com/upcoming/upcoming-www/commit/9e87c931ef1daba08a3654b0f82a77057b2c9a60
https://github.com/upcoming/upcoming-www/commit/4d06fc0322489d80eea1dcf380dfe115fa6eab27

**Comment by waxpancake** [comment]
Fixed!
