### ISSUE TITLE
Add Task Queue System

### ISSUE THREAD

**Issue by lhl** [upcoming/upcoming-www#16]
Almost has to be this just for the name
https://www.npmjs.com/package/barbeque
but it hasn't been updated in 2yrs

Bull is actively developed:
https://www.npmjs.com/package/bull

Kue is widely used, has had history of losing tasks?
https://github.com/Automattic/kue

Interesting lightweight solution (README has good comparison between options)
https://github.com/LewisJEllis/bee-queue

**Comment by waxpancake** [comment]
I'm going to wait on this. Thanks for the research.
