### ISSUE TITLE
Adding an Event: 502 Bad Gateway

### ISSUE THREAD

**Issue by stuffmc** [upcoming/upcoming-www#17]

**Comment by waxpancake** [comment]
Do you have any more detail on the error?

**Comment by stuffmc** [comment]
Not really. 

See https://www.dropbox.com/s/pl1us854mje9tar/Screenshot%202016-06-08%2000.18.35.png?dl=0

If I click “Add Event”, I have

502 Bad Gateway

nginx/1.4.6 (Ubuntu)

**Comment by waxpancake** [comment]
Hmm, worked for me:
https://beta.upcoming.org/event/swiftconf-16-gp7e4c0ftg

I have a feeling you might not be signed in... In which case, this is another bug—make sure users are prompted to authenticate when hitting the "Add Event" form.

**Comment by waxpancake** [comment]
This should be resolved now. I think I've squashed the last of the crashing errors.
