### ISSUE TITLE
Bug: Logging in --> 502 Bad Gateway

### ISSUE THREAD

**Issue by turoczy** [upcoming/upcoming-www#19]
The log in appears to complete if I back out of it, but it stalls at the 502 page.

**Comment by waxpancake** [comment]
@turoczy Does that happen every time you sign in? There were some temporary errors — I think because of load, still looking into it. Should be resolved now, though.

**Comment by turoczy** [comment]
@waxpancake May have been load. Logged out and logged back in with no issue.
