### ISSUE TITLE
No updates for 3 months

### ISSUE THREAD

**Issue by dvj** [upcoming/upcoming-www#6]

**Comment by waxpancake** [comment]
Hey, Doug! I'm wrapping up ticket sales for XOXO, and will get back to Upcoming development shortly with a substantial update. Sorry for the long delay.

**Comment by dvj** [comment]
ping

**Comment by gitunit** [comment]
looks like its dead

**Comment by waxpancake** [comment]
I wasn't happy with Python/Tornado, so ended up rewriting in Node/Express. Sorry about the long radio silence—I wasn't sure if it was something I was going to want to stick with or not.
